#!/bin/bash

# Load X resources (fixes some font issues)
xrdb -merge .Xresources
xsetroot -cursor_name left_ptr

# Desktop background
~/.fehbg

nm-applet &
redshift-gtk &
emacs --daemon &
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Compositing
compton &

# Set caps to ctrl
setxkbmap -option 'ctrl:nocaps'

exec xmonad
